# Generated by Django 4.2.2 on 2023-08-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='projects/'),
            preserve_default=False,
        ),
    ]
